import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ravendise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='font-Poppins text-3xl font-bold'>hello Ravendise</h1>
    </div>
  )
}
